# Generated by Django 3.2.5 on 2021-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_access_purchase_search_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sp',
        ),
    ]
